spring:
  mustache:
    suffix: .html
    expose-request-attributes: true

# ===============================
# DATABASE
# ===============================
  datasource:
    url: ${postgresql.url}
    username: ${postgresql.username}
    password: ${postgresql.pwd}
# Keep the connection alive if idle for a long time (needed in production)
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

# ===============================
# JPA / HIBERNATE
# ===============================
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# ----------------------------------------
# FLYWAY (FlywayProperties)
# ----------------------------------------
  flyway:
    table: flyway_schema_history
    baseline-on-migrate: true
    enabled: true

# ----------------------------------------
# OAUTH2
# ----------------------------------------
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - email
              - profile
        provider:
          google:
            user-name-attribute: email 
        
# ----------------------------------------
# PAYPAL
# ----------------------------------------            
paypal:
  mode: sandbox
  client:
    id: ${paypal.sandbox.id}
    secret: ${paypal.sandbox.secret}             